<?php

namespace App\Http\Requests\Diary;

use Illuminate\Foundation\Http\FormRequest;

class DiarySearchRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [

        ];
    }

    public function validated()
    {
        if(!$this->since_date) {
            $this->since_date = "1000-01-01";
        }
        if(!$this->until_date){
            $this->until_date = "9999-12-31";
        }
        return parent::validated(); // TODO: Change the autogenerated stub
    }
}
